//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIDatVe.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class APIQuanLy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public APIQuanLy()
        {
            this.QuyenAPIQuanLies = new HashSet<QuyenAPIQuanLy>();
        }
    
        public int APIquanlyid { get; set; }
        public string manhomapi { get; set; }
        public string actionname { get; set; }
        public string controllername { get; set; }
        public string mota { get; set; }
    
        public virtual NhomAPI NhomAPI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuyenAPIQuanLy> QuyenAPIQuanLies { get; set; }
    }
}
