//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIDatVe.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangGia
    {
        public int banggiaId { get; set; }
        public string madiemtrungchuyendon { get; set; }
        public string madiemtrungchuyentra { get; set; }
        public Nullable<double> giave { get; set; }
        public Nullable<double> thoigiandukien { get; set; }
    
        public virtual DiemTrungChuyen DiemTrungChuyen { get; set; }
        public virtual DiemTrungChuyen DiemTrungChuyen1 { get; set; }
    }
}
