//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIDatVe.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietVeXe
    {
        public int chitietvexeId { get; set; }
        public int vexeId { get; set; }
        public string maghe { get; set; }
        public string madiemtrungchuyendon { get; set; }
        public string madiemtrungchuyentra { get; set; }
        public Nullable<double> tongtien { get; set; }
    
        public virtual DiemChungChuyen DiemChungChuyen { get; set; }
        public virtual DiemChungChuyen DiemChungChuyen1 { get; set; }
        public virtual VeXe VeXe { get; set; }
    }
}
