//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIDatVe.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietLaiXe
    {
        public int chitietlaixeId { get; set; }
        public string manhanvien { get; set; }
        public string giaypheplaixe { get; set; }
        public string hanglai { get; set; }
        public string ngaycap { get; set; }
        public string noicap { get; set; }
        public string ghichu { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
