//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIDatVe.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DB : DbContext
    {
        public DB()
            : base("name=DB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<APIQuanLy> APIQuanLies { get; set; }
        public virtual DbSet<BangGia> BangGias { get; set; }
        public virtual DbSet<ChiTietLaiXe> ChiTietLaiXes { get; set; }
        public virtual DbSet<ChiTietLoTrinh> ChiTietLoTrinhs { get; set; }
        public virtual DbSet<ChiTietVeXe> ChiTietVeXes { get; set; }
        public virtual DbSet<ChucVu> ChucVus { get; set; }
        public virtual DbSet<ChuyenXe> ChuyenXes { get; set; }
        public virtual DbSet<DanhGia> DanhGias { get; set; }
        public virtual DbSet<DiemTrungChuyen> DiemTrungChuyens { get; set; }
        public virtual DbSet<DoiTuong> DoiTuongs { get; set; }
        public virtual DbSet<Ghe> Ghes { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<Kip> Kips { get; set; }
        public virtual DbSet<LoTrinh> LoTrinhs { get; set; }
        public virtual DbSet<ManHinhQuanLy> ManHinhQuanLies { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<NhomAPI> NhomAPIs { get; set; }
        public virtual DbSet<Quyen> Quyens { get; set; }
        public virtual DbSet<QuyenAPIQuanLy> QuyenAPIQuanLies { get; set; }
        public virtual DbSet<QuyenManHinhQuanLy> QuyenManHinhQuanLies { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
        public virtual DbSet<TaiKhoanCauHinh> TaiKhoanCauHinhs { get; set; }
        public virtual DbSet<TinhThanh> TinhThanhs { get; set; }
        public virtual DbSet<TrangThaiGhe> TrangThaiGhes { get; set; }
        public virtual DbSet<TrangThaiVeXe> TrangThaiVeXes { get; set; }
        public virtual DbSet<VeXe> VeXes { get; set; }
        public virtual DbSet<Xe> Xes { get; set; }
        public virtual DbSet<getBookingNotPayment> getBookingNotPayments { get; set; }
    
        public virtual ObjectResult<getTicketDetailByTicketID_Result> getTicketDetailByTicketID(string vexeid)
        {
            var vexeidParameter = vexeid != null ?
                new ObjectParameter("vexeid", vexeid) :
                new ObjectParameter("vexeid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getTicketDetailByTicketID_Result>("getTicketDetailByTicketID", vexeidParameter);
        }
    
        public virtual int sp_addFeedbackCustomer(string madanhgia, string makhachhang, string machuyenxe, Nullable<int> diemdanhgia, string noidungdanhgia)
        {
            var madanhgiaParameter = madanhgia != null ?
                new ObjectParameter("madanhgia", madanhgia) :
                new ObjectParameter("madanhgia", typeof(string));
    
            var makhachhangParameter = makhachhang != null ?
                new ObjectParameter("makhachhang", makhachhang) :
                new ObjectParameter("makhachhang", typeof(string));
    
            var machuyenxeParameter = machuyenxe != null ?
                new ObjectParameter("machuyenxe", machuyenxe) :
                new ObjectParameter("machuyenxe", typeof(string));
    
            var diemdanhgiaParameter = diemdanhgia.HasValue ?
                new ObjectParameter("diemdanhgia", diemdanhgia) :
                new ObjectParameter("diemdanhgia", typeof(int));
    
            var noidungdanhgiaParameter = noidungdanhgia != null ?
                new ObjectParameter("noidungdanhgia", noidungdanhgia) :
                new ObjectParameter("noidungdanhgia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_addFeedbackCustomer", madanhgiaParameter, makhachhangParameter, machuyenxeParameter, diemdanhgiaParameter, noidungdanhgiaParameter);
        }
    
        public virtual int sp_addTicket(string vexeid, string machuyenxe, string khachhangid, Nullable<int> matrangthaive, string tongtien, Nullable<int> sokhach, string ghichu, string madiemtrungchuyendon, string madiemtrungchuyentra)
        {
            var vexeidParameter = vexeid != null ?
                new ObjectParameter("vexeid", vexeid) :
                new ObjectParameter("vexeid", typeof(string));
    
            var machuyenxeParameter = machuyenxe != null ?
                new ObjectParameter("machuyenxe", machuyenxe) :
                new ObjectParameter("machuyenxe", typeof(string));
    
            var khachhangidParameter = khachhangid != null ?
                new ObjectParameter("khachhangid", khachhangid) :
                new ObjectParameter("khachhangid", typeof(string));
    
            var matrangthaiveParameter = matrangthaive.HasValue ?
                new ObjectParameter("matrangthaive", matrangthaive) :
                new ObjectParameter("matrangthaive", typeof(int));
    
            var tongtienParameter = tongtien != null ?
                new ObjectParameter("tongtien", tongtien) :
                new ObjectParameter("tongtien", typeof(string));
    
            var sokhachParameter = sokhach.HasValue ?
                new ObjectParameter("sokhach", sokhach) :
                new ObjectParameter("sokhach", typeof(int));
    
            var ghichuParameter = ghichu != null ?
                new ObjectParameter("ghichu", ghichu) :
                new ObjectParameter("ghichu", typeof(string));
    
            var madiemtrungchuyendonParameter = madiemtrungchuyendon != null ?
                new ObjectParameter("madiemtrungchuyendon", madiemtrungchuyendon) :
                new ObjectParameter("madiemtrungchuyendon", typeof(string));
    
            var madiemtrungchuyentraParameter = madiemtrungchuyentra != null ?
                new ObjectParameter("madiemtrungchuyentra", madiemtrungchuyentra) :
                new ObjectParameter("madiemtrungchuyentra", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_addTicket", vexeidParameter, machuyenxeParameter, khachhangidParameter, matrangthaiveParameter, tongtienParameter, sokhachParameter, ghichuParameter, madiemtrungchuyendonParameter, madiemtrungchuyentraParameter);
        }
    
        public virtual int sp_addTicketDetail(string chitietvexeid, string vexeid, string maghe, string tenhanhkhach, string sodienthoai, string doituong, string machuyenxe)
        {
            var chitietvexeidParameter = chitietvexeid != null ?
                new ObjectParameter("chitietvexeid", chitietvexeid) :
                new ObjectParameter("chitietvexeid", typeof(string));
    
            var vexeidParameter = vexeid != null ?
                new ObjectParameter("vexeid", vexeid) :
                new ObjectParameter("vexeid", typeof(string));
    
            var magheParameter = maghe != null ?
                new ObjectParameter("maghe", maghe) :
                new ObjectParameter("maghe", typeof(string));
    
            var tenhanhkhachParameter = tenhanhkhach != null ?
                new ObjectParameter("tenhanhkhach", tenhanhkhach) :
                new ObjectParameter("tenhanhkhach", typeof(string));
    
            var sodienthoaiParameter = sodienthoai != null ?
                new ObjectParameter("sodienthoai", sodienthoai) :
                new ObjectParameter("sodienthoai", typeof(string));
    
            var doituongParameter = doituong != null ?
                new ObjectParameter("doituong", doituong) :
                new ObjectParameter("doituong", typeof(string));
    
            var machuyenxeParameter = machuyenxe != null ?
                new ObjectParameter("machuyenxe", machuyenxe) :
                new ObjectParameter("machuyenxe", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_addTicketDetail", chitietvexeidParameter, vexeidParameter, magheParameter, tenhanhkhachParameter, sodienthoaiParameter, doituongParameter, machuyenxeParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_checkLogin(string sodienthoai, string matkhau)
        {
            var sodienthoaiParameter = sodienthoai != null ?
                new ObjectParameter("sodienthoai", sodienthoai) :
                new ObjectParameter("sodienthoai", typeof(string));
    
            var matkhauParameter = matkhau != null ?
                new ObjectParameter("matkhau", matkhau) :
                new ObjectParameter("matkhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_checkLogin", sodienthoaiParameter, matkhauParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_count_car_seatnumber(string maxe)
        {
            var maxeParameter = maxe != null ?
                new ObjectParameter("maxe", maxe) :
                new ObjectParameter("maxe", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_count_car_seatnumber", maxeParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_count_seat_empty_byTripID(string machuyenxe)
        {
            var machuyenxeParameter = machuyenxe != null ?
                new ObjectParameter("machuyenxe", machuyenxe) :
                new ObjectParameter("machuyenxe", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_count_seat_empty_byTripID", machuyenxeParameter);
        }
    
        public virtual ObjectResult<sp_getBookingTicketByCustomerID_Result> sp_getBookingTicketByCustomerID(string makhachhang)
        {
            var makhachhangParameter = makhachhang != null ?
                new ObjectParameter("makhachhang", makhachhang) :
                new ObjectParameter("makhachhang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getBookingTicketByCustomerID_Result>("sp_getBookingTicketByCustomerID", makhachhangParameter);
        }
    
        public virtual ObjectResult<sp_getInfoPointStartById_Result> sp_getInfoPointStartById(string madiemtrungchuyen)
        {
            var madiemtrungchuyenParameter = madiemtrungchuyen != null ?
                new ObjectParameter("madiemtrungchuyen", madiemtrungchuyen) :
                new ObjectParameter("madiemtrungchuyen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getInfoPointStartById_Result>("sp_getInfoPointStartById", madiemtrungchuyenParameter);
        }
    
        public virtual ObjectResult<sp_getListBookingTicketByCustomerID_Result> sp_getListBookingTicketByCustomerID(string makhachhang)
        {
            var makhachhangParameter = makhachhang != null ?
                new ObjectParameter("makhachhang", makhachhang) :
                new ObjectParameter("makhachhang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getListBookingTicketByCustomerID_Result>("sp_getListBookingTicketByCustomerID", makhachhangParameter);
        }
    
        public virtual ObjectResult<sp_getSechemaCar_Result> sp_getSechemaCar(string maxe)
        {
            var maxeParameter = maxe != null ?
                new ObjectParameter("maxe", maxe) :
                new ObjectParameter("maxe", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getSechemaCar_Result>("sp_getSechemaCar", maxeParameter);
        }
    
        public virtual ObjectResult<sp_getStatusSeatByTripId_Result> sp_getStatusSeatByTripId(string machuyenxe)
        {
            var machuyenxeParameter = machuyenxe != null ?
                new ObjectParameter("machuyenxe", machuyenxe) :
                new ObjectParameter("machuyenxe", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getStatusSeatByTripId_Result>("sp_getStatusSeatByTripId", machuyenxeParameter);
        }
    
        public virtual ObjectResult<sp_gettripbytripId_Result> sp_gettripbytripId(string malotrinh, Nullable<System.DateTime> ngayhoatdong)
        {
            var malotrinhParameter = malotrinh != null ?
                new ObjectParameter("malotrinh", malotrinh) :
                new ObjectParameter("malotrinh", typeof(string));
    
            var ngayhoatdongParameter = ngayhoatdong.HasValue ?
                new ObjectParameter("ngayhoatdong", ngayhoatdong) :
                new ObjectParameter("ngayhoatdong", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_gettripbytripId_Result>("sp_gettripbytripId", malotrinhParameter, ngayhoatdongParameter);
        }
    
        public virtual int sp_journey_book(string maghe, string machuyenxe, string khachhangId, Nullable<int> matrangthaive, string tongtien, Nullable<int> sokhach, string ghichu, string madiemtrungchuyendon, string madiemtrungchuyentra, string tenhanhkhach, string sodienthoaikhach, string doituong, Nullable<int> trangthai, string vexeId, string chitietvexeId)
        {
            var magheParameter = maghe != null ?
                new ObjectParameter("maghe", maghe) :
                new ObjectParameter("maghe", typeof(string));
    
            var machuyenxeParameter = machuyenxe != null ?
                new ObjectParameter("machuyenxe", machuyenxe) :
                new ObjectParameter("machuyenxe", typeof(string));
    
            var khachhangIdParameter = khachhangId != null ?
                new ObjectParameter("khachhangId", khachhangId) :
                new ObjectParameter("khachhangId", typeof(string));
    
            var matrangthaiveParameter = matrangthaive.HasValue ?
                new ObjectParameter("matrangthaive", matrangthaive) :
                new ObjectParameter("matrangthaive", typeof(int));
    
            var tongtienParameter = tongtien != null ?
                new ObjectParameter("tongtien", tongtien) :
                new ObjectParameter("tongtien", typeof(string));
    
            var sokhachParameter = sokhach.HasValue ?
                new ObjectParameter("sokhach", sokhach) :
                new ObjectParameter("sokhach", typeof(int));
    
            var ghichuParameter = ghichu != null ?
                new ObjectParameter("ghichu", ghichu) :
                new ObjectParameter("ghichu", typeof(string));
    
            var madiemtrungchuyendonParameter = madiemtrungchuyendon != null ?
                new ObjectParameter("madiemtrungchuyendon", madiemtrungchuyendon) :
                new ObjectParameter("madiemtrungchuyendon", typeof(string));
    
            var madiemtrungchuyentraParameter = madiemtrungchuyentra != null ?
                new ObjectParameter("madiemtrungchuyentra", madiemtrungchuyentra) :
                new ObjectParameter("madiemtrungchuyentra", typeof(string));
    
            var tenhanhkhachParameter = tenhanhkhach != null ?
                new ObjectParameter("tenhanhkhach", tenhanhkhach) :
                new ObjectParameter("tenhanhkhach", typeof(string));
    
            var sodienthoaikhachParameter = sodienthoaikhach != null ?
                new ObjectParameter("sodienthoaikhach", sodienthoaikhach) :
                new ObjectParameter("sodienthoaikhach", typeof(string));
    
            var doituongParameter = doituong != null ?
                new ObjectParameter("doituong", doituong) :
                new ObjectParameter("doituong", typeof(string));
    
            var trangthaiParameter = trangthai.HasValue ?
                new ObjectParameter("trangthai", trangthai) :
                new ObjectParameter("trangthai", typeof(int));
    
            var vexeIdParameter = vexeId != null ?
                new ObjectParameter("vexeId", vexeId) :
                new ObjectParameter("vexeId", typeof(string));
    
            var chitietvexeIdParameter = chitietvexeId != null ?
                new ObjectParameter("chitietvexeId", chitietvexeId) :
                new ObjectParameter("chitietvexeId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_journey_book", magheParameter, machuyenxeParameter, khachhangIdParameter, matrangthaiveParameter, tongtienParameter, sokhachParameter, ghichuParameter, madiemtrungchuyendonParameter, madiemtrungchuyentraParameter, tenhanhkhachParameter, sodienthoaikhachParameter, doituongParameter, trangthaiParameter, vexeIdParameter, chitietvexeIdParameter);
        }
    
        public virtual ObjectResult<sp_laythongtingiave_Result> sp_laythongtingiave(string madiemtrungchuyendon, string madiemtrungchuyentra)
        {
            var madiemtrungchuyendonParameter = madiemtrungchuyendon != null ?
                new ObjectParameter("madiemtrungchuyendon", madiemtrungchuyendon) :
                new ObjectParameter("madiemtrungchuyendon", typeof(string));
    
            var madiemtrungchuyentraParameter = madiemtrungchuyentra != null ?
                new ObjectParameter("madiemtrungchuyentra", madiemtrungchuyentra) :
                new ObjectParameter("madiemtrungchuyentra", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_laythongtingiave_Result>("sp_laythongtingiave", madiemtrungchuyendonParameter, madiemtrungchuyentraParameter);
        }
    
        public virtual ObjectResult<sp_listdiemtrungchuyen_Result> sp_listdiemtrungchuyen(string malotrinh)
        {
            var malotrinhParameter = malotrinh != null ?
                new ObjectParameter("malotrinh", malotrinh) :
                new ObjectParameter("malotrinh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_listdiemtrungchuyen_Result>("sp_listdiemtrungchuyen", malotrinhParameter);
        }
    
        public virtual ObjectResult<sp_search_customerbyusername_Result> sp_search_customerbyusername(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_search_customerbyusername_Result>("sp_search_customerbyusername", usernameParameter);
        }
    
        public virtual int sp_themkhachhang(string makhachhang, string hoten, string diachi, string sodienthoai, string email, string matkhau, string gioitinh)
        {
            var makhachhangParameter = makhachhang != null ?
                new ObjectParameter("makhachhang", makhachhang) :
                new ObjectParameter("makhachhang", typeof(string));
    
            var hotenParameter = hoten != null ?
                new ObjectParameter("hoten", hoten) :
                new ObjectParameter("hoten", typeof(string));
    
            var diachiParameter = diachi != null ?
                new ObjectParameter("diachi", diachi) :
                new ObjectParameter("diachi", typeof(string));
    
            var sodienthoaiParameter = sodienthoai != null ?
                new ObjectParameter("sodienthoai", sodienthoai) :
                new ObjectParameter("sodienthoai", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var matkhauParameter = matkhau != null ?
                new ObjectParameter("matkhau", matkhau) :
                new ObjectParameter("matkhau", typeof(string));
    
            var gioitinhParameter = gioitinh != null ?
                new ObjectParameter("gioitinh", gioitinh) :
                new ObjectParameter("gioitinh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_themkhachhang", makhachhangParameter, hotenParameter, diachiParameter, sodienthoaiParameter, emailParameter, matkhauParameter, gioitinhParameter);
        }
    
        public virtual int sp_update_password_customer(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_update_password_customer", usernameParameter, passwordParameter);
        }
    
        public virtual int sp_updateCustomeInfo(string makhachhang, string tenkhachhang, string sodienthoai, string diachi, string gioitinh, string matkhau, string email)
        {
            var makhachhangParameter = makhachhang != null ?
                new ObjectParameter("makhachhang", makhachhang) :
                new ObjectParameter("makhachhang", typeof(string));
    
            var tenkhachhangParameter = tenkhachhang != null ?
                new ObjectParameter("tenkhachhang", tenkhachhang) :
                new ObjectParameter("tenkhachhang", typeof(string));
    
            var sodienthoaiParameter = sodienthoai != null ?
                new ObjectParameter("sodienthoai", sodienthoai) :
                new ObjectParameter("sodienthoai", typeof(string));
    
            var diachiParameter = diachi != null ?
                new ObjectParameter("diachi", diachi) :
                new ObjectParameter("diachi", typeof(string));
    
            var gioitinhParameter = gioitinh != null ?
                new ObjectParameter("gioitinh", gioitinh) :
                new ObjectParameter("gioitinh", typeof(string));
    
            var matkhauParameter = matkhau != null ?
                new ObjectParameter("matkhau", matkhau) :
                new ObjectParameter("matkhau", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_updateCustomeInfo", makhachhangParameter, tenkhachhangParameter, sodienthoaiParameter, diachiParameter, gioitinhParameter, matkhauParameter, emailParameter);
        }
    
        public virtual int sp_updateSeatStatusNotPayment()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_updateSeatStatusNotPayment");
        }
    
        public virtual int updatetrangthaighe(string maghe, Nullable<int> trangthai, string vexeid, Nullable<int> matrangthaive)
        {
            var magheParameter = maghe != null ?
                new ObjectParameter("maghe", maghe) :
                new ObjectParameter("maghe", typeof(string));
    
            var trangthaiParameter = trangthai.HasValue ?
                new ObjectParameter("trangthai", trangthai) :
                new ObjectParameter("trangthai", typeof(int));
    
            var vexeidParameter = vexeid != null ?
                new ObjectParameter("vexeid", vexeid) :
                new ObjectParameter("vexeid", typeof(string));
    
            var matrangthaiveParameter = matrangthaive.HasValue ?
                new ObjectParameter("matrangthaive", matrangthaive) :
                new ObjectParameter("matrangthaive", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updatetrangthaighe", magheParameter, trangthaiParameter, vexeidParameter, matrangthaiveParameter);
        }
    }
}
