//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIDatVe.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhanVien()
        {
            this.ChiTietLaiXes = new HashSet<ChiTietLaiXe>();
            this.ChuyenXes = new HashSet<ChuyenXe>();
            this.ChuyenXes1 = new HashSet<ChuyenXe>();
        }
    
        public string manhanvien { get; set; }
        public string hoten { get; set; }
        public string machucvu { get; set; }
        public Nullable<System.DateTime> ngaysinh { get; set; }
        public string diachi { get; set; }
        public string sodienthoai { get; set; }
        public string email { get; set; }
        public string socmt { get; set; }
        public string ngaycap { get; set; }
        public string tentaikhoan { get; set; }
        public string noicap { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietLaiXe> ChiTietLaiXes { get; set; }
        public virtual ChucVu ChucVu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChuyenXe> ChuyenXes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChuyenXe> ChuyenXes1 { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
