//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIDatVe.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuyenManHinhQuanLy
    {
        public int quyenmanhinhquanlyId { get; set; }
        public int manhinhquanlyId { get; set; }
        public string maquyen { get; set; }
        public bool chon { get; set; }
    
        public virtual ManHinhQuanLy ManHinhQuanLy { get; set; }
        public virtual Quyen Quyen { get; set; }
    }
}
