//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIDatVe.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        public string tentaikhoan { get; set; }
        public string maquyen { get; set; }
        public string matkhau { get; set; }
        public string hoten { get; set; }
        public string email { get; set; }
        public Nullable<int> solandangnhapsai { get; set; }
        public Nullable<int> trangthai { get; set; }
        public string linklaylaitaikhoan { get; set; }
        public Nullable<System.DateTime> thoigianyeucaulaylaitk { get; set; }
    
        public virtual Quyen Quyen { get; set; }
    }
}
