//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIDatVe.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaiKhoan()
        {
            this.NhanViens = new HashSet<NhanVien>();
            this.TaiKhoanCauHinhs = new HashSet<TaiKhoanCauHinh>();
        }
    
        public string tentaikhoan { get; set; }
        public string maquyen { get; set; }
        public string matkhau { get; set; }
        public string hoten { get; set; }
        public string email { get; set; }
        public Nullable<int> solandangnhapsai { get; set; }
        public Nullable<int> trangthai { get; set; }
        public string linklaylaitaikhoan { get; set; }
        public Nullable<System.DateTime> thoigianyeucaulaylaitk { get; set; }
        public string avatar { get; set; }
        public string gioitinh { get; set; }
        public string diachi { get; set; }
        public Nullable<System.DateTime> ngaysinh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhanVien> NhanViens { get; set; }
        public virtual Quyen Quyen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaiKhoanCauHinh> TaiKhoanCauHinhs { get; set; }
    }
}
