//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIDatVe.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoanCauHinh
    {
        public int taikhoancauhinhId { get; set; }
        public string tentaikhoan { get; set; }
        public string cauhinh { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
