//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIDatVe.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrangThaiGhe
    {
        public int trangthaigheId { get; set; }
        public string maghe { get; set; }
        public Nullable<System.DateTime> ngay { get; set; }
        public Nullable<int> trangthai { get; set; }
        public string machuyenxe { get; set; }
    
        public virtual Ghe Ghe { get; set; }
    }
}
